CREATE DATABASE DB_CLIENTES

USE DB_CLIENTES

CREATE TABLE [dbo].[T_CLIENTE] (
    [ID]        INT          IDENTITY (1, 1) NOT NULL,
    [NOME]      VARCHAR (20) NOT NULL,
    [SOBRENOME] VARCHAR (20) NOT NULL,
    [RG]        VARCHAR (9)  NULL,
    [CPF]       VARCHAR (11) NULL,
    [CNPJ]      VARCHAR (14) NULL,
    [TIPO]      CHAR (1)     NOT NULL,
    CONSTRAINT [PK_T_CLIENTE] PRIMARY KEY CLUSTERED ([ID] ASC)
);

CREATE TABLE [dbo].[T_TELEFONE] (
    [ID]         INT      IDENTITY (1, 1) NOT NULL,
    [DDD]        CHAR (2) NULL,
    [NUMERO]     CHAR (9) NOT NULL,
    [TIPO]       CHAR (1) NOT NULL,
    [ID_CLIENTE] INT      NOT NULL,
    CONSTRAINT [PK_TELEFONE] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_TELEFONE_T_CLIENTE] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [dbo].[T_CLIENTE] ([ID])
);


CREATE TABLE [dbo].[T_ENDERECO] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL,
    [CEP]         CHAR (9)      NOT NULL,
    [LOGRADOURO]  VARCHAR (100) NOT NULL,
    [NUMERO]      VARCHAR (5)   NULL,
    [COMPLEMENTO] VARCHAR (50)  NULL,
    [BAIRRO]      VARCHAR (30)  NOT NULL,
    [CIDADE]      VARCHAR (30)  NOT NULL,
    [UF]          VARCHAR (2)   NOT NULL,
    [ID_CLIENTE]  INT           NOT NULL,
    CONSTRAINT [PK_T_ENDERECO] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [FK_T_ENDERECO_T_CLIENTE] FOREIGN KEY ([ID_CLIENTE]) REFERENCES [dbo].[T_CLIENTE] ([ID])
);